// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1pATfoF9wApdeyNuqdZAekxa6171CMe8',
    appId: '1:974652821981:web:6017826dfea2dc0703a634',
    messagingSenderId: '974652821981',
    projectId: 'sokratesflutter-2',
    authDomain: 'sokratesflutter-2.firebaseapp.com',
    storageBucket: 'sokratesflutter-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbz4GCr5-VRzbZCROHVFEJ7Y9ntYbuEE',
    appId: '1:974652821981:android:b69089bd7a4b3c4003a634',
    messagingSenderId: '974652821981',
    projectId: 'sokratesflutter-2',
    storageBucket: 'sokratesflutter-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7lwJX8qnn2TwhyR_7lffNtHz94fwHIcI',
    appId: '1:974652821981:ios:1490835c3c39341a03a634',
    messagingSenderId: '974652821981',
    projectId: 'sokratesflutter-2',
    storageBucket: 'sokratesflutter-2.firebasestorage.app',
    iosBundleId: 'com.example.session92',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7lwJX8qnn2TwhyR_7lffNtHz94fwHIcI',
    appId: '1:974652821981:ios:1490835c3c39341a03a634',
    messagingSenderId: '974652821981',
    projectId: 'sokratesflutter-2',
    storageBucket: 'sokratesflutter-2.firebasestorage.app',
    iosBundleId: 'com.example.session92',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1pATfoF9wApdeyNuqdZAekxa6171CMe8',
    appId: '1:974652821981:web:1e22245737824e1b03a634',
    messagingSenderId: '974652821981',
    projectId: 'sokratesflutter-2',
    authDomain: 'sokratesflutter-2.firebaseapp.com',
    storageBucket: 'sokratesflutter-2.firebasestorage.app',
  );
}
