// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3dAZJ6oE1lrKjY2CBDa-Cg90HGDnP-Gc',
    appId: '1:446388736944:web:d0caf55c9871368977bc75',
    messagingSenderId: '446388736944',
    projectId: 'sokratesflutter-1',
    authDomain: 'sokratesflutter-1.firebaseapp.com',
    storageBucket: 'sokratesflutter-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9KiAv09v8bIiHFvIxBWIEYXpM93yfsp8',
    appId: '1:446388736944:android:47c07456ad05f45d77bc75',
    messagingSenderId: '446388736944',
    projectId: 'sokratesflutter-1',
    storageBucket: 'sokratesflutter-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ZfGRwSQcNBfmMYbaVyopAcWech0SjTk',
    appId: '1:446388736944:ios:9a7dbf52adad8f8877bc75',
    messagingSenderId: '446388736944',
    projectId: 'sokratesflutter-1',
    storageBucket: 'sokratesflutter-1.firebasestorage.app',
    iosBundleId: 'com.example.session91',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ZfGRwSQcNBfmMYbaVyopAcWech0SjTk',
    appId: '1:446388736944:ios:9a7dbf52adad8f8877bc75',
    messagingSenderId: '446388736944',
    projectId: 'sokratesflutter-1',
    storageBucket: 'sokratesflutter-1.firebasestorage.app',
    iosBundleId: 'com.example.session91',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3dAZJ6oE1lrKjY2CBDa-Cg90HGDnP-Gc',
    appId: '1:446388736944:web:60c9d8e81f25cb7077bc75',
    messagingSenderId: '446388736944',
    projectId: 'sokratesflutter-1',
    authDomain: 'sokratesflutter-1.firebaseapp.com',
    storageBucket: 'sokratesflutter-1.firebasestorage.app',
  );
}
