import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file will be generated by the FlutterFire CLI if you use it

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase; you can pass default options if generated by FlutterFire CLI.
  await Firebase.initializeApp(
    // If you haven't used FlutterFire CLI, you might leave this empty or provide options manually.
    // options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Firebase Integration',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Firebase Integration'),
      ),
      body: const Center(
        child: Text('Firebase is integrated!'),
      ),
    );
  }
}
